name: Ubuntu environment
on: 
  push:
    branches: 
      - master
env:
  MOZ_FETCHES_DIR: /home/runner/fetches
  MOZBUILD_STATE_PATH: /home/runner/.mozbuild

jobs:
  fx_build:
    name: Iceweasel build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: mkdir and setenv
      id: mkdir_setenv
      run: |
        mkdir "$MOZ_FETCHES_DIR"
        mkdir -p "$MOZBUILD_STATE_PATH"
        echo LIBPORTABLE_PATH=$MOZ_FETCHES_DIR/clang>>$GITHUB_ENV
        echo VC_REDISTDIR=$MOZ_FETCHES_DIR/vs/VC>>$GITHUB_ENV
        cd $GITHUB_WORKSPACE
        pwd
        ls -la
      shell: bash
      
    - name: Show env
      id: env_path
      run: |
        echo LIBPORTABLE_PATH [$LIBPORTABLE_PATH]
        echo VC_REDISTDIR [$VC_REDISTDIR]
        echo HOME [$HOME]
        env
        pwd
        gcc -v
        python --version
        which 7z
        which node
        which wget
        which gcc
        df -HT /home
      shell: bash

    - name: Download Tools
      id: build_tools
      run: |
        cd $MOZ_FETCHES_DIR
        wget https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/U1Vn8JFpQIyJia7ngQxtRg/artifacts/public/build/wine.tar.zst
        tar xvf wine.tar.zst
        WINEPREFIX=$MOZ_MOZ_FETCHES_DIR/.wine wine/bin/wine64 --version
      shell: bash