name: Ubuntu environment
on: 
  push:
    branches: 
      - master
env:
  MOZ_FETCHES_DIR: /builds/worker/fetches
  MOZBUILD_DOWNLOAD: /builds/worker/fetches/download
  MOZBUILD_STATE_PATH: /builds/worker/fetches/.mozbuild


jobs:
  fx_build:
    name: Iceweasel build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: disk df
      id: disk_df
      run: |
        df -h
      shell: bash

    - uses: mathio/gha-cleanup@v1
      with:
        remove-browsers: true
        verbose: true

    - name: mkdir and setenv
      id: mkdir_setenv
      run: |
        sudo mkdir -p "$MOZ_FETCHES_DIR"
        sudo chown runner:runner -R "$MOZ_FETCHES_DIR"
        mkdir -p "$MOZBUILD_DOWNLOAD"
        echo LIBPORTABLE_PATH=$MOZ_FETCHES_DIR/clang>>$GITHUB_ENV
        echo VC_REDISTDIR=$MOZ_FETCHES_DIR/vs/VC>>$GITHUB_ENV
        cd $GITHUB_WORKSPACE
        pwd
        ls -la
        df -h
      shell: bash
      
    - name: Show env
      id: env_path
      run: |
        echo LIBPORTABLE_PATH [$LIBPORTABLE_PATH]
        echo VC_REDISTDIR [$VC_REDISTDIR]
        echo HOME [$HOME]
        env
        pwd
        gcc -v
        python --version
        which 7z
        which node
        which wget
        which gcc
        df -HT /home
        node --version
      shell: bash

    - name: Download Tools
      id: build_tools
      run: |
        cd "$MOZBUILD_DOWNLOAD"
        wget https://master.dl.sourceforge.net/project/libportable/Mozillabuild/cbindgen.tar.xz?viasf=1 -O cbindgen.tar.xz
        if [ $? -ne 0 ]; then
          echo Download cbindgen failed
          exit 255
        fi
        ls -la
        tar Jxf cbindgen.tar.xz -C "$MOZ_FETCHES_DIR"
        ls "$MOZ_FETCHES_DIR" -la
        # WINEPREFIX=$MOZ_MOZ_FETCHES_DIR/.wine wine/bin/wine64 --version
      shell: bash