name: Ubuntu environment
on: 
  push:
    branches: 
      - master
env:
  FETCHES_DIR: /home/runner/fetches
  OBJ_DIR: /home/runner/obju-release

jobs:
  fx_build:
    name: Iceweasel build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: mkdir and setenv
      id: mkdir_setenv
      run: |
        mkdir "$FETCHES_DIR"
        mkdir -p "$OBJ_DIR"
        echo LIBPORTABLE_PATH=$FETCHES_DIR/clang>>$GITHUB_ENV
        echo VC_REDISTDIR=$FETCHES_DIR/vs/VC>>$GITHUB_ENV
        cd $GITHUB_WORKSPACE
        pwd
        ls -la
      shell: bash
      
    - name: Show env
      id: env_path
      run: |
        echo LIBPORTABLE_PATH [$LIBPORTABLE_PATH]
        echo VC_REDISTDIR [$VC_REDISTDIR]
        echo HOME [$HOME]
        env
        pwd
        gcc -v
        python --version
        which 7z
        which node
        which gcc
      shell: bash