name: Windows environment
on: 
  push:
    branches: 
      - master
      - release
env:
  BUID_DIR: d:\works
  SOURCE_DIR: d:\works\3rdparty

jobs:
  fx_build:
    name: Iceweasel build
    runs-on: windows-2019
    steps:        
    - uses: actions/checkout@v3

    - name: mkdir and setenv
      id: mkdir_setenv
      run: |
        mkdir "%BUID_DIR%"
        echo LIBPORTABLE_PATH=%BUID_DIR%\mozillabuild\clang>>%GITHUB_ENV%
        echo VC_REDISTDIR=%VCToolsRedistDir%>>%GITHUB_ENV%
        cd /d %GITHUB_WORKSPACE%
        type config\milestone.txt|findstr "[1-9]">tmp_1.txt
        set /p m_ver=<tmp_1.txt
        del /q tmp_1.txt >nul
        echo MY_VER=%m_ver%>>%GITHUB_ENV%
      shell: cmd
      
    - name: Add path
      id: env_path
      run: |
        echo "%LIBPORTABLE_PATH%\bin">>%GITHUB_PATH%
      shell: cmd

    - name: msvc64 environment
      id: msvc64
      run: |
        echo MY_BITS64=win64>>%GITHUB_ENV%
      shell: cmd
      
    - name: Show all env64
      id: env_show64
      run: |
        @set
      shell: cmd
      
    - name: Start cmake build64
      id: cmake_build64
      run: |
        cd /d %GITHUB_WORKSPACE%
        if not defined MY_BITS64 echo MY_BITS64 not defined.&EXIT /B 4
        @echo we build win64&call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64"
        mkdir ..\build&&cd ..\build
        cmake ../actions_test -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
        nmake
        cd /d %GITHUB_WORKSPACE%
        ..\build\main.exe
        7z a -aoa "main-%MY_VER%-%MY_BITS64%.7z" "..\build"
      shell: cmd
      
    - name: msvc32 environment
      id: msvc32
      run: |
        echo MY_BITS32=win32>>%GITHUB_ENV%
      shell: cmd
      
    - name: Show all env32
      id: env_show32
      run: |
        @set
      shell: cmd
            
    - name: Start cmake build32
      id: cmake_build32
      run: |
        cd /d %GITHUB_WORKSPACE%
        if not defined MY_BITS32 echo MY_BITS32 not defined.&EXIT /B 4
        @echo we build win32&call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32"
        rd /s /q "..\build"
        mkdir "..\build"&&cd "..\build"
        cmake ../actions_test -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
        nmake
        cd /d %GITHUB_WORKSPACE%
        ..\build\main.exe
        7z a -aoa "main-%MY_VER%-%MY_BITS32%.7z" "..\build"
      shell: cmd

    - uses: actions/upload-artifact@v3
      with:
        path: ${{ github.workspace }}/main-${{ env.MY_VER }}-${{ env.MY_BITS64 }}.7z
        name: main-${{ env.MY_VER }}-${{ env.MY_BITS64 }}

    - uses: actions/upload-artifact@v3
      with:
        path: ${{ github.workspace }}/main-${{ env.MY_VER }}-${{ env.MY_BITS32 }}.7z
        name: main-${{ env.MY_VER }}-${{ env.MY_BITS32 }}
 
    - name: Get current time
      uses: yxl0756/get-current-time@v2.0.2
      id: current-time
      with:
        format: YYYYMMDDHHmmss
        utcOffset: "+08:00"

    - name: Create Release
      id: create_release
      uses: yxl0756/create-release@1a72e235c178bf2ae6c51a8ae36febc24568c5fe
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN_YXL0756 }}
      with:
        tag_name: ${{ steps.current-time.outputs.time }}
        release_name: Release ${{ steps.current-time.outputs.time }}
        commitish: master
        draft: false
        prerelease: false

    - name: Store Release url    
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url

    - uses: actions/upload-artifact@v3
      with:
        path: ./upload_url
        name: upload_url

    - uses: yxl0756/release-action@v1.12.0
      with:
        artifacts: ${{ github.workspace }}/main-${{ env.MY_VER }}-${{ env.MY_BITS32 }}.7z
        prerelease: false
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        
    - uses: yxl0756/release-action@v1.12.0
      with:
        artifacts: ${{ github.workspace }}/main-${{ env.MY_VER }}-${{ env.MY_BITS64 }}.7z
        prerelease: false
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
                